version: '3'

networks:
  default:
    external:
      name: middleware

services:
  devicemanager:
    build: ./device-manager
    container_name: devicemanager
    ports:
     - ${DEVICE_MANAGER_PORT}:${DEVICE_MANAGER_PORT}
    depends_on:
      - devicemanager-mongo
    
  devicemanager-mongo:
    image: mongo
    container_name: devicemanager-mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DEVICE_MANAGER_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DEVICE_MANAGER_DB_PASSWORD}
    ports: 
      - ${DEVICE_MANAGER_DB_PORT}:${DEVICE_MANAGER_DB_PORT}

    