version: '3'

networks:
  default:
    external:
      name: middleware

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  serviceregistry:
    build: ./service-registry
    container_name: serviceregistry
    ports:
      - ${SERVICE_REGISTRY_PORT}:${SERVICE_REGISTRY_PORT}
    depends_on: 
      - redis

    