version: "3"

networks:
  default:
    external:
      name: moreiot

volumes:
  npm-cache:
    external: false

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:${REDIS_HOST}:${REDIS_PORT}
    ports:
      - "8081:8081"
    depends_on: 
      - redis
  serviceregistry:
    build: ./service-registry
    container_name: serviceregistry
    volumes:
      - npm-cache:/root/.npm
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
    ports:
      - ${SERVICE_REGISTRY_PORT}:${SERVICE_REGISTRY_PORT}
    depends_on: 
      - redis
  devicemanager:
    build: ./device-manager
    container_name: devicemanager
    volumes:
      - npm-cache:/root/.npm
    environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - DEVICE_MANAGER_PORT=${DEVICE_MANAGER_PORT}
    ports:
      - ${DEVICE_MANAGER_PORT}:${DEVICE_MANAGER_PORT}
    depends_on:
      - serviceregistry
  datamanager:
    build: ./data-manager
    container_name: datamanager
    volumes:
      - npm-cache:/root/.npm
    environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - DATA_MANAGER_PORT=${DATA_MANAGER_PORT}
    ports:
      - ${DATA_MANAGER_PORT}:${DATA_MANAGER_PORT}
    depends_on:
      - serviceregistry
  actionmanager:
    build: ./action-manager
    container_name: actionmanager
    volumes:
      - npm-cache:/root/.npm
    environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - ACTION_MANAGER_PORT=${ACTION_MANAGER_PORT}
    ports:
      - ${ACTION_MANAGER_PORT}:${ACTION_MANAGER_PORT}
    depends_on:
      - serviceregistry
  servicecataloger:
    build: ./service-cataloger
    container_name: servicecataloger
    volumes:
      - npm-cache:/root/.npm
    environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - SERVICE_CATALOGER_PORT=${SERVICE_CATALOGER_PORT}
    ports:
      - ${SERVICE_CATALOGER_PORT}:${SERVICE_CATALOGER_PORT}
    depends_on:
      - serviceregistry
  inputcommunicator:
   build: ./input-communicator
   container_name: inputcommunicator
   volumes:
    - npm-cache:/root/.npm
   environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - INPUT_COMMUNICATOR_PORT=${INPUT_COMMUNICATOR_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - RABBITMQ_PUBLISHER_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PUBLISHER_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SUBSCRIBER_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_SUBSCRIBER_PASSWORD=${RABBITMQ_DEFAULT_PASS}
   ports:
     - ${INPUT_COMMUNICATOR_PORT}:${INPUT_COMMUNICATOR_PORT}
   depends_on:
     - serviceregistry
     - rabbitmq
     - redis
  actioncommunicator:
    build: ./action-communicator
    container_name: actioncommunicator
    volumes:
      - npm-cache:/root/.npm
    environment:
      - SERVICE_REGISTRY_HOST=${SERVICE_REGISTRY_HOST}
      - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
      - ACTION_COMMUNICATOR_PORT=${ACTION_COMMUNICATOR_PORT}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - RABBITMQ_PUBLISHER_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PUBLISHER_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SUBSCRIBER_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_SUBSCRIBER_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${ACTION_COMMUNICATOR_PORT}:${ACTION_COMMUNICATOR_PORT}
    depends_on:
      - serviceregistry
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management-alpine
    command: '/bin/bash -c "rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_management; rabbitmq-server"'
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
  # node-red:
  #   image: nodered/node-red:latest
  #   ports:
  #     - 1880:1880
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
  #   ports:
  #     - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
