version: '3'

networks:
  default:
    external:
      name: middleware

services:
  devicemanager:
    build: ./device-manager
    container_name: devicemanager
    ports:
     - ${DEVICE_MANAGER_PORT}:${DEVICE_MANAGER_PORT}
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    container_name: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    ports: 
      - ${MONGO_PORT}:${MONGO_PORT}
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    